#!/bin/bash

yum update -y

yum install httpd.x86_64 -y
systemctl start httpd.service
systemctl enable httpd.service 

## Extra-steps for AZ information

EC2_AVAIL_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
echo "<h1>Hello World, from $(hostname -f), in AZ $EC2_AVAIL_ZONE </h1>" > /var/www/html/index.html